### ISSUE TITLE
Socket_MessageReceived is never called.

### ISSUE THREAD

**Issue by AvinashDeluxeVR** [littilewing/UnityOSC#1]
Hi there,

Firstly, thank you for making this. Unfortunately, this isn't working for me. :(

So I have the following capabilities enabled in my package.appxmanifest:
internet (client & server)
internet (client)
Private Networks (client and server)

A connection in OSCServer.cs is established, but the function Socket_MessageReceived is never called/executed. Here's my debug output.

`
OSCClient Connect start...
OSCClient Connect finished:172.16.80.2
OSCCLIENT-SEND:/test/alive/
SUCCESS: send OSC packet to client 172.16.80.2 : 9000:Length44
Waiting for a connection...
SUCCESS: opened the server at the given port. 172.16.80.2 : 8000`

I never see:

`OSCSERVER UWP  Socket_MessageReceived`

Any thoughts?

Avinash.

**Comment by AvinashDeluxeVR** [comment]
Ignore this, I had the loopback issue.

**Comment by the6th** [comment]
@AvinashDeluxeVR 
sorry for late reply.i have prepared sample unity project for hololens(tests/touchosc_integration/)

please try it.

**Comment by AvinashDeluxeVR** [comment]
Thanks! I was able to work around it. I didn't realize that local machine IPC using Loopback on UWP is restricted.  See note on https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DatagramSocket
